Update example data files and move Sand & Gravel to new location
ONSdigital/sds-schema-definitions pull request #8
Opened 2024-03-26 08:44 UTC by liamtoozer

### What is the context of this PR?

To allow [eQ Launcher](https://github.com/ONSdigital/eq-questionnaire-launcher) to launch business SDS schemas such as BRES, Roofing Tiles etc, the example SDS data in this repository needs to be updated so that the [eQ Mock SDS](https://github.com/ONSdigital/eq-runner-mock-sds) service can return the example data. 

The changes for this PR are as follows:
* Move 'Sand & Gravel' example data and docs into separate folders
* Rename existing 'Roofing Tiles & Slate' examples & docs
* Update example data file names to reflect `identifier` `12345678901`- eQ Launcher currently uses this hardcoded identifier to allow the surveys to be launched in non-production test environments, so the example files have been renamed to reflect this.

### Links
https://jira.ons.gov.uk/browse/ECI-1122

### Checklist

* [ ] Changes to the spec have been added to example schemas in [examples/](/examples/)
* [ ] JSON Schema definitions have been updated

2024-03-26 09:22 UTC, MebinAbraham commented on examples/sand_and_gravel/12345678901.json
> +{
The file names should stay the same as they represent the schema versions. If we wanted multiple examples for each schema version, then they should be in a folder with the version name.

so either `v1.json` or `v1/<file_name>.json` (if we wanted multiple examples)

2024-03-27 16:28 UTC, MebinAbraham reviewed
The folder structure should be consistent between schemas/ and examples/. One is folder by survey then version, the other is by version then survey. Survey then by version is my preference.

2024-04-11 12:39 UTC, Jon-Kent approved these changes

2024-04-11 13:55 UTC, martyncolmer approved these changes

2024-04-12 08:21 UTC, tidmanmike approved these changes

2024-04-16 12:14 UTC, MebinAbraham approved these changes

2024-04-16 12:14 UTC, MebinAbraham requested changes

2024-04-16 12:14 UTC, MebinAbraham commented on README.md
> +./scripts/validateSchemas.js schemas/v1/v1.json examples/prodcom/v1.json
This seems incorrect.

2024-04-16 12:45 UTC, MebinAbraham approved these changes

2024-04-23 10:45 UTC, merged